-- Tabla para almacenar las metas de encuestas por sede
CREATE TABLE IF NOT EXISTS sedes_metas (
  id SERIAL PRIMARY KEY,
  sede_id INTEGER REFERENCES sedes(id) ON DELETE CASCADE,
  meta_total INTEGER NOT NULL DEFAULT 0,
  fecha_inicio DATE NOT NULL DEFAULT '2026-04-01',
  fecha_fin DATE NOT NULL DEFAULT '2026-12-31',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(sede_id)
);

-- Habilitar RLS
ALTER TABLE sedes_metas ENABLE ROW LEVEL SECURITY;

-- Políticas para sedes_metas (solo lectura pública)
DROP POLICY IF EXISTS "sedes_metas_select" ON sedes_metas;
CREATE POLICY "sedes_metas_select" ON sedes_metas FOR SELECT USING (true);

-- Insertar las metas por sede usando el nombre para encontrar el id
INSERT INTO sedes_metas (sede_id, meta_total, fecha_inicio, fecha_fin)
SELECT s.id, m.meta, '2026-04-01', '2026-12-31'
FROM (VALUES
  ('ABREGO', 7),
  ('AGUACHICA', 18),
  ('ARATOCA', 29),
  ('ASTREA', 3),
  ('BAJO RIONEGRO', 4),
  ('BARBOSA', 1),
  ('BARICHARA', 27),
  ('BARRANCABERMEJA', 250),
  ('BARRANCABERMEJA 2', 43),
  ('BOCHALEMA', 17),
  ('BOGOTA ENGATIVA', 6),
  ('BOGOTA RESTREPO', 6),
  ('BOGOTA USAQUEN', 6),
  ('BOSCONIA', 0),
  ('BUCA CABECERA', 193),
  ('BUCA CABECERA POSITIVA', 25),
  ('BUCA MUTIS', 23),
  ('BUCA NORTE', 51),
  ('BUCARASICA', 7),
  ('CABRERA', 9),
  ('CACHIRA', 10),
  ('CANTAGALLO', 17),
  ('CAPITANEJO', 17),
  ('CARCASI', 11),
  ('CERRITO', 21),
  ('CHARALA', 28),
  ('CHIMA', 3),
  ('CHIMICHAGUA', 2),
  ('CHINACOTA', 20),
  ('CHITAGA', 32),
  ('CIMITARRA', 51),
  ('CODAZZI', 2),
  ('CONCEPCION', 29),
  ('CONTRATACION', 18),
  ('COROMORO', 9),
  ('CUCUTA CAOBOS', 250),
  ('CUCUTA CAOBOS POSITIVA', 52),
  ('CUCUTA DIG SANT', 250),
  ('CUCUTA FOMAG', 29),
  ('CUCUTA LA PLAYA', 89),
  ('CUCUTA POPULAR', 250),
  ('CUCUTA POPULAR 2', 196),
  ('CUCUTA QUINTA ORI', 243),
  ('CUCUTA TUCUNARE', 109),
  ('CURITI', 35),
  ('CURUMANI', 1),
  ('EL CARMEN DE CHUCURI', 15),
  ('EL COPEY', 4),
  ('EL GUACAMAYO', 9),
  ('EL TARRA', 26),
  ('EL ZULIA', 70),
  ('ENCINO', 10),
  ('ENCISO', 17),
  ('FLORIDABLANCA', 50),
  ('GALAN', 11),
  ('GAMARRA', 2),
  ('GIRON', 122),
  ('GUACA', 16),
  ('GUADALUPE', 19),
  ('JESUS MARIA', 14),
  ('LA BELLEZA', 6),
  ('LA ESPERANZA', 17),
  ('LA JAGUA DE IBIRICO', 3),
  ('LA PAZ (STDR)', 12),
  ('LABATECA', 24),
  ('LEBRIJA', 61),
  ('LOS PATIOS', 117),
  ('LOS SANTOS', 18),
  ('MALAGA', 61),
  ('MOLAGAVITA', 14),
  ('OCAMONTE', 16),
  ('OCAÑA BULEVAR', 250),
  ('OCAÑA CENTRO', 18),
  ('OIBA', 21),
  ('PAILITAS', 3),
  ('PALMAS DEL SOCORRO', 11),
  ('PAMPLONA', 63),
  ('PARAMO', 14),
  ('PELAYA', 2),
  ('PTO STDER', 14),
  ('PUENTE NACIONAL', 33),
  ('PUERTO WILCHES', 21),
  ('RIO DE ORO', 16),
  ('RIONEGRO', 30),
  ('SABANA DE TORRES', 2),
  ('SALAZAR', 13),
  ('SAN ALBERTO', 13),
  ('SAN ANDRES', 22),
  ('SAN CAYETANO', 17),
  ('SAN GIL', 176),
  ('SAN JOSE MIRANDA', 13),
  ('SAN MARTIN', 2),
  ('SAN VICENTE DE CHUCURI', 62),
  ('SARDINATA', 30),
  ('SIMACOTA', 17),
  ('SOCORRO', 81),
  ('SURATA', 10),
  ('TAMALAMEQUE', 1),
  ('TOLEDO', 20),
  ('VALLE DE SAN JOSE', 20),
  ('VALLEDUPAR', 45),
  ('VELEZ', 16),
  ('VILLA DEL ROSARIO', 121),
  ('ZAPATOCA', 22)
) AS m(nombre, meta)
JOIN sedes s ON UPPER(s.nombre) = m.nombre
ON CONFLICT (sede_id) DO UPDATE SET 
  meta_total = EXCLUDED.meta_total,
  updated_at = NOW();
